version: '3.8'

services:
    postgres:
        image: ${POSTGRES_IMAGE:-postgres:15.2}
        container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
        volumes:
            - ./volumes/postgresql/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        restart: always
        networks:
            - postgres

    adminer:
        image: ${ADMINER_IMAGE:-adminer:4.8.1}
        container_name: ${ADMINER_CONTAINER_NAME:-adminer}       
        ports:
            - ${ADMINER_PORT:-8080}:8080
        restart: always
        networks:
            - postgres

networks:
    postgres:
        name: postgres
